config/routes.rb
Rails.application.routes.draw do

  resources :surveys

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers

  validates :question, presence: true
  validates :kind, presence: true

end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :surveys

  has_secure_password

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def self.authenticate_with_credentials(email, password)
    user = User.where("LOWER(email)=?", email.strip.downcase).first
    if user && user.authenticate(password)
      user
    else
      false
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # def new
  #   @question = Question.new
  # end

  def create
    @survey = Survey.find(params[:survey_id])
    @question = @survey.questions.create(question_params)
  end

  def update
  end

  def destroy
  end

  private

  def question_params
    params.require(:question).permit(:question, :kind)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # If the user exists AND the password entered is correct.
    if user = User.authenticate_with_credentials(params[:email], params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/surveys'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def new
    @survey = Survey.new
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def create
    @survey = Survey.new(survey_params)
    @user = current_user
    @survey.user = @user
    @survey.save!

    if @survey.save
      redirect_to surveys_path
    else
      render :new
    end
  end

  def update
    @survey = Survey.find(params[:id])

    if @survey.update_attributes(survey_params)
      redirect_to survey_path(@survey)
    else
      render :edit
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_path
  end

  protected

  def survey_params
    params.require(:survey).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to surveys_path
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyGoat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_create.html.erb
<%= form_for :question, url: survey_questions_path(:survey_id), html: {class: "new-question"} do |f| %>
  <p>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </p>

  <p>
    <%= f.label :type %><br>
    <%= f.select :kind, options_for_select(["Plain Text", "MC", "SC"]) %>
  </p>
  <%= hidden_field_tag :survey_id, survey_id %>
<% end %>

app/views/surveys/edit.html.erb
<h1>Survey#edit</h1>
<p> <%= "#{@survey.title}" %> </p>

<%= link_to "Delete this Survey", @survey, method: :delete, data: { confirm: "Are you sure?" } %>

<%= form_for @survey, url: survey_path(@survey), method: :patch, html: {class: "edit-survey"} do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= render '/questions/create', survey_id: @survey.id %>

app/views/surveys/index.html.erb
<h1> Surveys </h1>

<% if current_user %>
  <li id="signed-in">
    Signed in as <%= current_user.email %></li>
  <li> <%= link_to "Logout", '/logout' %></li>
<% else %>
  <li> <%= link_to 'Login', '/login' %></li>
  <li> <%= link_to 'Signup', '/signup' %></li>
<% end %>



<% @surveys.each do | survey | %>
  <td>
    <%= "#{survey.title}" %>
    <%= link_to "View Survey", survey_path(survey) %>
    <%= link_to "Edit Survey", edit_survey_path(survey) %>
  </td>
<% end %>

<%= link_to "Create New Survey", new_survey_path %>

app/views/surveys/new.html.erb
<h1> Create a new survey! </h1>

<%= form_for :survey, url: surveys_path do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@survey.errors.count, "error") %> prohibited
        this survey from being saved:
      </h2>
      <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/surveys/show.html.erb
<h1>Survey#show</h1>
<p> <%= "#{@survey.title}" %> </p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %> <br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div><%= f.submit "Submit" %></div>
  <% end %>